### ISSUE TITLE
Suggestion: Add relative count or percentage for (1M+?) subs

### ISSUE THREAD

**Issue by FabulousCupcake** [Tanza3D/reddark#10]
Something like the following to give more sense of scale:
<img width="582" alt="Screenshot 2023-06-09 at 10 18 19 AM" src="https://github.com/Tanza3D/reddark/assets/25855364/6846bcca-53f5-41cb-95c9-556fb0bead02">

Might be nicer shown as percentage, maybe also with color (how close it is to 100%).

I found the information about number of subs with certain sub count at https://subredditstats.com/list/most-subscribers.  
Make sure to change the filter to include `sfw+nsfw`.

Since the numbers for 5M+ are quite small (<50) it might also be worth just listing all of them explicitly, not just the ones participating (for 30M, 20M, 10M, and 5M brackets only).

———

If this sounds good I can whip up a PR later

**Comment by username-is-required** [comment]
Just as an FYI, the way the proposed design looks in the screenshot was a little confusing to me - at first glance I thought “6 out of 10”, “9 out of 20”, etc. referred to the number of subs in that bracket that *had gone dark* (out of the number that have committed to going dark), rather than the number of subs that have **committed** to going dark *out of the total number of subs in that bracket*.

My personal opinion is that I’m opposed to this change, mainly on the basis that it would be another piece of information to be displayed & would potentially clutter the UI. Personally, I’m in favour of keeping the UI quite minimalist/clean in the way that it is at the moment.

To be honest I suppose it depends on what the purpose of the website is judged to be - whether it’s for getting an idea of the % of subreddits that have joined the blackout, just to be able to watch with satisfaction on June 12th as all . Personally, I’m in favour of keeping the UI quite minimalist

(To be clear this is in no way an attack at your suggestion! I think it’s a cool idea, it’s just my personal preference is just for the site to remain in more of a minimalistic state.)

At the end of the day though it’s @Tanza3D’s site so it’s his call :)

**Comment by username-is-required** [comment]
Just as an FYI, the way the proposed design looks in the screenshot was a little confusing to me - at first glance I thought “6 out of 10”, “9 out of 20”, etc. referred to the number of subs in that bracket that had *gone dark* (out of the number that have committed to going dark), rather than the number of subs that have *committed* to going dark ***out of the total number of subs in that bracket***.

My personal opinion is that I’m opposed to this proposed change, mainly on the basis that it would be another piece of information to be displayed & would potentially clutter the UI. Personally, I’m in favour of keeping the UI quite minimalist/clean in the way that it is at the moment.

To be honest I suppose it depends on what the purpose of the website is judged to be - on the scale between ‘just watching in satisfaction as the subreddits go dark’/‘just getting an idea of what subreddits are dark at that moment in time’ and ‘being able to understand more of the proportions of the blackout/the number of subs that are dark as a % of the subreddit population’. Personally I’d place my usage of the site nearer to the former options (as in, just watching in satisfaction as the subs go dark/seeing at a glance how many & what subreddits are currently dark). [That’s not to say that there wouldn’t be a **place** for the latter information, but that in my opinion it might be better as a separate site dedicated to providing that data.]

(To be clear this is in no way an attack at your suggestion! I think it’s a cool idea, it’s just my personal preference is just for the site to remain in more of a minimalistic state. And I’m sorry if I come across as harsh/blunt at all in this comment, that’s not my intention whatsoever!)

I’d also personally be tentatively opposed to displaying all the subreddits with 5M+ subscribers. I guess this boils down again to the intended usage/purpose of the site, but I’d personally be watching it to see how many subs have gone private **out of those that have declared they’ll go private** - and following the count at the top of the page as well in that regard. To me, including subs that haven’t stated that they’re part of the blackout would skew the purpose of the site (and the count) a little bit. (Of course, it’s possible that a large subreddit that *hasn’t* said it’s going private will suddenly black out in protest, however in that circumstance I’d expect it would be quickly added to the list of participating subreddits, and then picked up by this page when the server refreshes the list.)

At the end of the day though it’s @Tanza3D’s site so it’s his call what happens about any of this :)

**Comment by Tanza3D** [comment]
yeah, this wouldn't be great i feel. from a UX standpoint people would expect that to be how many are dark out of how many are planned to go dark, and although i would love to add that counter, the idea you have would just stand to confuse people.

to @username-is-required - the idea for the site is kind of just both, if you want to watch them all go dakr you can, but if you want to get an idea of how many are dark that should be supported too. 

definitely shouldn't display all the subreddits

i like the idea of show how much of each section is actively dark though, could definitely see that as being nice, should be reasonably easy to add

**Comment by FabulousCupcake** [comment]
I think it's a nice opportunity for the site/page to do that extra mile and be informative; there's a great value/oomph showing e.g. 100% of 30M+ subreddits are going dark, rather than just 10 (no idea how many are out there). UX or how it displayed is something that can be figured out.

That being said I'll close the issue since I won't be pushing/working on it
